#!/bin/bash

rosservice call /reset
rosparam set /background_r 175
rosparam set /background_g 179
rosparam set /background_b 250
rosservice call /clear
rosservice call /turtle1/set_pen 255 255 255 3 1
rosservice call /turtle1/teleport_absolute 1 5 0
rosservice call /turtle1/set_pen 113 66 140 3 0

function space() {
	rosservice call /turtle1/set_pen 0 0 0 3 1
	rosservice call /turtle1/teleport_relative 2.0616 1.3258
	rosservice call /turtle1/teleport_relative "linear: 0.0
angular: -1.3258" 
	rosservice call /turtle1/set_pen 113 66 140 3 0
}

function two() {
	rosservice call /turtle1/teleport_relative 1 0
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 1.57
}

function four() {
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 2 3.1415
	rosservice call /turtle1/teleport_relative 0 1.57
}

function three() {
	rosservice call /turtle1/teleport_relative 1 0
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 3.1415
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 3.1415
}

function nine() {
	rosservice call /turtle1/set_pen 0 0 0 3 1
	rosservice call /turtle1/teleport_relative "linear: 1.414213
angular: -0.7853981"
	rosservice call /turtle1/teleport_relative 0 0.7853981
	rosservice call /turtle1/set_pen 113 66 140 3 0
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 4.71
	rosservice call /turtle1/teleport_relative 1 3.1415
	
}

function six() {
	rosservice call /turtle1/teleport_relative 1 0
	rosservice call /turtle1/teleport_relative 1 3.1415
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 0
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/teleport_relative 1 1.57
	rosservice call /turtle1/set_pen 0 0 0 3 1
	rosservice call /turtle1/teleport_relative 0 3.1415
	rosservice call /turtle1/teleport_relative "linear: 1.414213
angular: -0.7853981"
	rosservice call /turtle1/teleport_relative 0 0.7853981
}

function seven() {
	rosservice call /turtle1/teleport_relative 1 0
	rosservice call /turtle1/teleport_relative 2 4.71
	rosservice call /turtle1/teleport_relative 0 1.57
}

two
space
four
space
three
space
nine
space
six
space
seven
space
